# Generated by Django 5.1.2 on 2024-11-07 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('u_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('u_nome', models.CharField(max_length=100)),
                ('u_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='tarefas',
            fields=[
                ('t_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('t_setor', models.CharField(max_length=100)),
                ('t_prioridades', models.CharField(max_length=100)),
                ('t_status', models.CharField(max_length=100)),
                ('t_data', models.DateField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.usuarios')),
            ],
        ),
    ]
