# Generated by Django 5.1.2 on 2024-11-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tarefas',
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
    ]
